//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WACol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fecNacimiento { get; set; }
        public string estadoCivil { get; set; }
        public string gradoAcademico { get; set; }
        public string direccion { get; set; }
    }
}
